### ISSUE TITLE
Data manipulation and mark/filter the GPW13 indicators 

### ISSUE THREAD

**Issue by dhyougit** [amitprasad531/gpw13-dashboard#1]
@amitprasad531 

The first issues to clear is data manipulation in below two aspects 

-  **Build a coherent format** of data file so that it can be pulled by universal pipeline code to build a dashboard. Currently, 2016,2017, and 2018 dataset is completed for its unified format across three years of data so that we can start from that file. 

 The format of data from the rest of years (goes back to around 2000 depends on indicator) can be designed to match with 2016-2018 WHS dataset.  

-  **Mark GPW13 related indicators from the source file** and drop all other indicators from the WHS dataset that is not relevant to GPW13 indicators.

**Comment by dhyougit** [comment]
Data source file updated to clear issues of "mark GPW13 related indicators" from the above issue. 

**Similarity**   : 

- Empty= no equivalent GPW indicator, 
- 0 = somehow matches, 
- 0.5 = almost   identical definition, 
- 1= Identical


| Colnam| Definition |
| ------------- | ------------- |
| GPW_number    | GPW programmatic target number (Source: EB144/7 Annex 4)  |
| GPW_name  | GPW programmatic target title (Source: EB144/7 Annex 4)   |
| GPW_benchmark  | GPW programmatic benchmark value/target (Source: EB 144/7 Annex 4)  |

**Comment by amitprasad531** [comment]
- The first issue of having a coherent file has already been addressed with the file whs.csv using the WHS2016to2018 excel sheet created by Doohee.

- This is not very difficult and can be done programmatically in R (keeping only GPW 13 indicators).

**Comment by dhyougit** [comment]
GPW13 indicator flag is corporated to each of the three years data file and updated under 'data' folder. 
GPW_WHS_2016.csv
GPW_WHS_2017.csv
GPW_WHS_2018.csv
